---
title: "TV_vs_INT"
author: "Brandon Wolff"
date: "June 15, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Thesis

```{r cars}
#load and subset data
Proj <- read.csv("Gaming_Jobs_TV_Broadband.csv") # Data is from Pew Research Center (Internet and Technology)    
                                                 # http://www.pewinternet.org/datasets/  
                                                 # Titled : June 10 - July 12, 2015 - Gaming, Jobs and Broadband

vars <- Proj[c("emplnw", "age", "educ2", "inc", "ï..psraid")]

myvars <- names(Proj) %in% c("emplnw", "age", "educ2", "inc") 
Proj <- Proj[!myvars]



# Change to NA
Proj[Proj == 8] <- NA # IDK
Proj[Proj == 9] <- NA # NA

vars[vars == 98] <- NA #IDK
vars[vars == 99] <- NA #NA

# mAKE EMPLOYMENT 1,2,3  
vars$emplnw[vars$emplnw == 3 | vars$emplnw == 4 | vars$emplnw == 6 | vars$emplnw == 7 | vars$emplnw == 8] <- 3
vars$emplnw[vars$emplnw == 5] <- 1
summary(vars$emplnw)

# Married or not
Proj$marital[Proj$marital == 3 | Proj$marital == 4 | Proj$marital == 5 | Proj$marital == 6] <- 2
summary(Proj$marital)
table(Proj$par)
# reverse code
Proj[,c("cable2", "cable3c", "cable3a", "cable3b",  "sex", "marital", "par", "home4nw", "intmob", "bbsmart1", "bbsmart2", "bbsmart3a", "bbsmart3b", "bbsmart3c", "bbsmart3d", "bbsmart3e", "bbsmart3f")] <- 2-Proj[,c("cable2", "cable3c", "cable3a", "cable3b",  "sex", "marital", "par", "home4nw", "intmob", "bbsmart1", "bbsmart2", "bbsmart3a", "bbsmart3b", "bbsmart3c", "bbsmart3d", "bbsmart3e", "bbsmart3f")]

Proj[,c("cable1")] <- 2-Proj[,c("cable1")]

summary(Proj$cable2)

# reverse code
vars[,c("emplnw")] <- 3-vars[,c("emplnw")]


Proj[,c("stud")] <- 3-Proj[,c("stud")]


Proj[,c("intfreq")] <- -Proj[,c("intfreq")]

Proj1 <- merge(Proj, vars, by = "ï..psraid")

table(Proj1$race)

# create new variable for generations
attach(Proj1)
Proj1$genage <- Proj1$age[age > 79] <- "G.I_Gen"
Proj1$genage[age > 70 & age <= 78] <- "Silent_Gen"
Proj1$genage[age > 61 & age <= 69] <- "Older_Boomers"
Proj1$genage[age > 51 & age <= 60] <- "Young_Boomers"
Proj1$genage[age > 35 & age <= 50] <- "Gen_X"
Proj1$genage[age <= 34] <- "Millennials"
detach(Proj1)


#make as factor and use a reference group

# millennials as REF 
table(Proj1$genage)
Proj1$genage <- as.factor(Proj1$genage)
Proj1 <- within(Proj1, genage <- relevel(genage, ref = 3))

# white as ref

Proj1$race[Proj1$race == "1"] <- "White"
Proj1$race[Proj1$race == "2"] <- "Black or African-American"
Proj1$race[Proj1$race == "3"] <- "Asian or Pacific Islander"
Proj1$race[Proj1$race == "4"] <- "Mixed race"
Proj1$race[Proj1$race == "5"] <- "Native American/American Indian"
Proj1$race[Proj1$race == "6"] <- "Other"

Proj1$race <- as.factor(Proj1$race)
Proj1 <- within(Proj1, race <- relevel(race, ref = 6))

table(Proj1$race)


# midwest as ref. group

Proj1$cregion[Proj1$cregion == "1"] <- "Northeast"
Proj1$cregion[Proj1$cregion == "2"] <- "Midwest"
Proj1$cregion[Proj1$cregion == "3"] <- "South"
Proj1$cregion[Proj1$cregion == "4"] <- "West"

#create variable for cable vs not

Proj1$cabletest[Proj1$cable1 == 1] <- 1
Proj1$cabletest[Proj1$cable1 == 0 & Proj1$cable3a == 1 & Proj1$cable3b == 0 & Proj1$cable3c == 0] <- 2
Proj1$cabletest[Proj1$cable1 == 0 & Proj1$cable3a == 0 & Proj1$cable3b == 1 & Proj1$cable3c == 0] <- 3
Proj1$cabletest[Proj1$cable1 == 0 & Proj1$cable3a == 0 & Proj1$cable3b == 0 & Proj1$cable3c == 1] <- 4

Proj1$sumtest = Proj1$cable3a + Proj1$cable3b + Proj1$cable3c
table(Proj1$sumtest)

Proj1$cabletest[Proj1$cable1 == 0 & Proj1$sumtest > 1] <- 5
table(Proj1$cabletest)

#create variable for hom int vs not

Proj1$home_inttest[Proj1$bbhome1 == 2] <- 1

Proj1$home_inttest[Proj1$bbhome1 == 3] <- 1

Proj1$home_inttest[Proj1$bbhome2 == 2] <- 1

Proj1$home_inttest[Proj1$bbsmart4 == 1] <- 2

Proj1$home_inttest[Proj1$bbsmart3a == 1 & Proj1$bbsmart3b == 0 & Proj1$bbsmart3c == 0 & Proj1$bbsmart3d == 0 & Proj1$bbsmart3e == 0 & Proj1$bbsmart3f == 0] <- 2

Proj1$home_inttest[Proj1$bbsmart4 == 2] <- 3

Proj1$home_inttest[Proj1$bbsmart3a == 0 & Proj1$bbsmart3b == 1 & Proj1$bbsmart3c == 0 & Proj1$bbsmart3d == 0 & Proj1$bbsmart3e == 0 & Proj1$bbsmart3f == 0] <- 3

Proj1$home_inttest[Proj1$bbsmart4 == 3] <- 4

Proj1$home_inttest[Proj1$bbsmart3a == 0 & Proj1$bbsmart3b == 0 & Proj1$bbsmart3c == 1 & Proj1$bbsmart3d == 0 & Proj1$bbsmart3e == 0 & Proj1$bbsmart3f == 0] <- 4

Proj1$home_inttest[Proj1$bbsmart4 == 4] <- 5

Proj1$home_inttest[Proj1$bbsmart3a == 0 & Proj1$bbsmart3b == 0 & Proj1$bbsmart3c == 0 & Proj1$bbsmart3d == 1 & Proj1$bbsmart3e == 0 & Proj1$bbsmart3f == 0] <- 5

Proj1$home_inttest[Proj1$bbsmart4 == 5] <- 6

Proj1$home_inttest[Proj1$bbsmart3a == 0 & Proj1$bbsmart3b == 0 & Proj1$bbsmart3c == 0 & Proj1$bbsmart3d == 0 & Proj1$bbsmart3e == 1 & Proj1$bbsmart3f == 0] <- 6

Proj1$home_inttest[Proj1$bbsmart4 == 6] <- 7

Proj1$home_inttest[Proj1$bbsmart3a == 0 & Proj1$bbsmart3b == 0 & Proj1$bbsmart3c == 0 & Proj1$bbsmart3d == 0 & Proj1$bbsmart3e == 0 & Proj1$bbsmart3f == 1] <- 7


table(Proj1$home_inttest)
table(Proj1$home4nw)
table(Proj1$bbsmart4)
table(Proj1$bbhome2)


#create variable for cable vs not AGAIN

Proj1$cable_cat[Proj1$cable1 == 1] <- 1
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 1 & Proj1$cable3b == 0 & Proj1$cable3c == 0] <- 2
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 0 & Proj1$cable3b == 1 & Proj1$cable3c == 0] <- 3
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 0 & Proj1$cable3b == 0 & Proj1$cable3c == 1] <- 4
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 1 & Proj1$cable3b == 1 & Proj1$cable3c == 0] <- 5
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 1 & Proj1$cable3b == 0 & Proj1$cable3c == 1] <- 6
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 0 & Proj1$cable3b == 1 & Proj1$cable3c == 1] <- 7
Proj1$cable_cat[Proj1$cable1 == 0 & Proj1$cable3a == 1 & Proj1$cable3b == 1 & Proj1$cable3c == 1] <- 8

table(Proj1$cable_cat)
table(Proj1$emplnw)
 
```

# Hypothesis 1

```{r}
glm1 <- glm(intmob ~ genage + marital + par + race + cregion + inc + stud + educ2 + sex, data = Proj1, family = "binomial")
summary(glm1)
exp(coef(glm1))
table(Proj1$inc)
table(Proj1$inc_cat)
```

# Hypothesis 2

```{r}

glm2 <- glm(cable1 ~ intmob + sex + genage + marital + par + race + cregion + inc + stud + educ2, data = Proj1, family = "binomial")
summary(glm2)
exp(coef(glm2))

glm3 <- glm(home4nw ~ intmob + sex + genage + marital + par + race + cregion + inc + stud + educ2, data = Proj1, family = "binomial")
summary(glm3)
exp(coef(glm3))

```

# Hypothesis 3

```{r}
#create new variable for income
attach(Proj1)
Proj1$inc_cat <- Proj1$inc[inc > 7] <- "High"
Proj1$inc_cat[inc > 4 & inc <= 7] <- "Middle"
Proj1$inc_cat[inc <= 3] <- "Low"
detach(Proj1)
table(Proj1$inc_cat)

library(nnet)

## build internet model 

table(Proj1$bbsmart4)

Proj1$home_inttest <- factor(Proj1$home_inttest, labels = c("Broadband internet", "Expensive", "No Computer Cost", "Mobile Internet", " No Outside of Home", "Not Available", "No Other"))
table(Proj1$home_inttest)

Proj1 <- within(Proj1, home_inttest <- relevel(home_inttest, ref = "Broadband internet"))

multinom_home_int1 <- multinom(home_inttest ~ bbsmart1 + bbsmart2 + race + inc_cat + stud + marital + educ2 + par + sex + genage + intmob + intfreq +  cable1 + cregion , Proj1)
multinom_home_int <- multinom(home_inttest ~ race + intfreq, Proj1)

summary(multinom_home_int1)

z1 <- summary(multinom_home_int1)$coefficients/summary(multinom_home_int1)$standard.errors
z1

# 2-tailed z test
p1 <- (1 - pnorm(abs(z1), 0, 1)) * 2
p1

## extract the coefficients from the model and exponentiate
exp(coef(multinom_home_int1))

head(pp <- fitted(multinom_home_int1))


drace <- data.frame(race = c("White", "Black or African-American", "Asian or Pacific Islander", "Mixed race", "Native American/American Indian", "Other"), intfreq = mean(Proj1$intfreq, na.rm = TRUE))
predict(multinom_home_int, newdata = drace, "probs")


dfreq <- data.frame(race = rep(c("White", "Black or African-American", "Asian or Pacific Islander", "Mixed race", "Native American/American Indian", "Other"), each = 70), intfreq = rep(c(0:4),
    2))


pp.freq <- cbind(dfreq, predict(multinom_home_int, newdata = dfreq, type = "probs", se = TRUE))


by(pp.freq[, 3:9], pp.freq$race, colMeans)



mytable1 <- table(Proj1$home_inttest, Proj1$intmob) 
ftable(mytable1)
```

# Hypothesis 4

```{r}

Proj1$cabletest <- factor(Proj1$cabletest, labels = c("cable", "dont_watch", "No_cost", "internet", "multi_reason"))
table(Proj1$cabletest)

Proj1 <- within(Proj1, cabletest <- relevel(cabletest, ref = "cable"))

multinom_cable1 <- multinom(cabletest ~ cable2 + race + inc_cat + stud + marital + educ2 + par + sex + genage + intmob + intfreq + home4nw + as.factor(cregion), Proj1)
multinom_cable <- multinom(cabletest ~ race + inc, Proj1)

summary(multinom_cable)

z <- summary(multinom_cable1)$coefficients/summary(multinom_cable1)$standard.errors
z

# 2-tailed z test
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p

## extract the coefficients from the model and exponentiate
exp(coef(multinom_cable))

head(pp <- fitted(multinom_cable))

```

```{r}
# fixed cable model

Proj1$cable_cat <- factor(Proj1$cable_cat, labels = c("cable", "dont_watch", "cost", "internet", "DontWatch_Cost", "DontWatch_Internet", "Cost_Internet", "All_Reasons"))
table(Proj1$cable_cat)

Proj1 <- within(Proj1, cable_cat <- relevel(cable_cat, ref = "cable"))



multinom_cable3 <- multinom(cable_cat ~ cable2 + race + inc_cat + stud + marital + educ2 + par + sex + genage + intmob + intfreq + emplnw + home4nw + as.factor(cregion), Proj1)
multinom_cable <- multinom(cable_cat ~ race + intfreq, Proj1)

summary(multinom_cable)

z3 <- summary(multinom_cable3)$coefficients/summary(multinom_cable3)$standard.errors
z3

# 2-tailed z test
p3 <- (1 - pnorm(abs(z3), 0, 1)) * 2
p3

## extract the coefficients from the model and exponentiate
exp(coef(multinom_cable3))

head(pp <- fitted(multinom_cable3))

drace2 <- data.frame(race = c("White", "Black or African-American", "Asian or Pacific Islander", "Mixed race", "Native American/American Indian", "Other"), intfreq = mean(Proj1$intfreq, na.rm = TRUE))
predict(multinom_cable, newdata = drace2, "probs")


dfreq2 <- data.frame(race = rep(c("White", "Black or African-American", "Asian or Pacific Islander", "Mixed race", "Native American/American Indian", "Other"), each = 70), intfreq = rep(c(0:4),
    2))


pp.freq2 <- cbind(dfreq2, predict(multinom_cable, newdata = dfreq2, type = "probs", se = TRUE))


by(pp.freq2[, 3:10], pp.freq2$race, colMeans)

```

# visualizations

```{r}
library(reshape2)
library(ggplot2)

```

```{r}

lpp3 <- melt(pp.freq2, id.vars = c("race", "intfreq"), value.name = "probability")
head(lpp3)  


ggplot(lpp3, aes(x = intfreq, y = probability, colour = race)) + geom_line() + facet_grid(variable ~
    ., scales = "free")

```

```{r}

lpp2 <- melt(pp.freq, id.vars = c("race", "intfreq"), value.name = "probability")
head(lpp2)  


ggplot(lpp2, aes(x = intfreq, y = probability, colour = race)) + geom_line() + facet_grid(variable ~
    ., scales = "free")
```

```{r}
viz <- Proj1
viz[,c("intmob")] <- 1+viz[,c("intmob")]
table(viz$intmob)

multinom_intvmob <- multinom(home_inttest ~ intmob + intfreq, viz)


dmob <- data.frame(intmob = c(1, 2), intfreq = mean(viz$intfreq, na.rm = TRUE))
predict(multinom_intvmob, newdata = dmob, "probs")


dfreqm <- data.frame(intmob = rep(c(1, 2), each = 70), intfreq = rep(c(0:4),
    2))

pp.freqm <- cbind(dfreqm, predict(multinom_intvmob, newdata = dfreqm, type = "probs", se = TRUE))


by(pp.freqm[, 3:9], pp.freqm$intmob, colMeans)


lpp4 <- melt(pp.freqm, id.vars = c("intmob", "intfreq"), value.name = "probability")
head(lpp4)  


lpp4$intmob[lpp4$intmob == "1"] <- "Do Not"
lpp4$intmob[lpp4$intmob == "2"] <- "Use the mobile internet"

ggplot(lpp4, aes(x = intfreq, y = probability, colour = intmob)) + geom_line() + facet_grid(variable ~
    ., scales = "free")
```

```{r}
viz <- Proj1
viz[,c("intmob")] <- 1+viz[,c("intmob")]
table(viz$intmob)

mnc <- multinom(cable_cat ~ intmob + intfreq, viz)


dmob2 <- data.frame(intmob = c(1, 2), intfreq = mean(viz$intfreq, na.rm = TRUE))
predict(mnc, newdata = dmob2, "probs")


dfreqm2 <- data.frame(intmob = rep(c(1, 2), each = 70), intfreq = rep(c(0:4),
    2))


pp.freqm2 <- cbind(dfreqm2, predict(mnc, newdata = dfreqm2, type = "probs", se = TRUE))


by(pp.freqm2[, 3:10], pp.freqm2$intmob, colMeans)


lpp5 <- melt(pp.freqm2, id.vars = c("intmob", "intfreq"), value.name = "probability")
head(lpp5)  


lpp5$intmob[lpp5$intmob == "1"] <- "Do Not"
lpp5$intmob[lpp5$intmob == "2"] <- "Use the mobile internet"

ggplot(lpp5, aes(x = intfreq, y = probability, colour = intmob)) + geom_line() + facet_grid(variable ~
    ., scales = "free")
```
# Final visualization for Thesis
```{r fig.width=10, fig.height=10}

mnc3 <- multinom(cable_cat ~ genage + intfreq, Proj1)


dgenage <- data.frame(genage = c("Millennials", "Gen_X", "Young_Boomers", "Older_Boomers", "Silent_Gen", "G.I_Gen"), intfreq = mean(Proj1$intfreq, na.rm = TRUE))
predict(mnc3, newdata = dgenage, "probs")


dfreq3 <- data.frame(genage = rep(c("Millennials", "Gen_X", "Young_Boomers", "Older_Boomers", "Silent_Gen", "G.I_Gen"), each = 70), intfreq = rep(c(0:4),
    2))


pp.freqm3 <- cbind(dfreq3, predict(mnc3, newdata = dfreq3, type = "probs", se = TRUE))


by(pp.freqm3[, 3:10], pp.freqm3$genage, colMeans)


lpp6 <- melt(pp.freqm3, id.vars = c("genage", "intfreq"), value.name = "probability")
head(lpp5) 



ggplot(lpp6, aes(x = intfreq, y = probability, colour = genage)) + geom_line(size=1.5) + facet_grid(variable ~
    ., scales = "free") + scale_colour_brewer(palette = "Dark2")
```
