---
title: "word_fataframe/Cluster"
author: "Brandon Wolff and Chih-Chin Tien"
date: "December 1, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## K-means Clustering

Using K- means to explore the data and see potential groupings.

```{r}
library(tm)



docs <- Corpus(DirSource("wordstrain"))

mystopwords=c("i'm","'re",'but','many','and',"can",'good','know','ll','will','one','now',"re","ve","don't","get","well","back","let's","dont","tell","every","yes","everyone","right","much","anyone","lets","just","ever","isn't","still","let","said","ago","right","see","couldn't","wanted","even","tonight","things","others","going","like","way","make","also","applause","years","small","big","want","new","first","state","better","day","must","put","next","longer","never","come","made","time","guy","real","really","got","movie","film","watching","something","actually","another","man","movies","littl","use","give","find","thing","work","movi","onli","very","films","think","character","scene","isnt","doesnt","thats","around","cant","didnt","lot","might","theres","take","say","quite","may","however","though","watch","seen","gets","without","almost","wasnt","making","seems","yet","ive","seems","bit","thought","saw","last","played","done","makes","plays","kind","part","whole","later","hes","although","sure","always","times","since","probably","far","feel","little", "two", "people")

docs <- tm_map(docs, removePunctuation)

for(j in seq(docs))   
   {   
     docs[[j]] <- gsub("/", " ", docs[[j]])   
     docs[[j]] <- gsub("@", " ", docs[[j]])   
     docs[[j]] <- gsub("\\|", " ", docs[[j]])   
}   

docs <- tm_map(docs, removeNumbers) 

docs <- tm_map(docs, tolower)

docs <- tm_map(docs,removeWords,c(stopwords("en"),mystopwords)) 

```

```{r}
 library(SnowballC)   
docs <- tm_map(docs, stemDocument)   

docs <- tm_map(docs, stripWhitespace)

docs <- tm_map(docs, PlainTextDocument)

```

```{r}
dtm <- DocumentTermMatrix(docs)   
dtm

tdm <- TermDocumentMatrix(docs)   
tdm

dtms <- removeSparseTerms(dtm, 0.1) 
```

```{r}
freq <- sort(colSums(as.matrix(dtms)), decreasing=TRUE)   
head(freq, 14)
```

```{r}
freq50 <- findFreqTerms(dtm, lowfreq=50)
```


```{r}
wf <- data.frame(word=names(freq), freq=freq)   
head(wf)
```

```{r}
View(wf)
```

```{r}
tdm <- tdm[names(tail(sort(rowSums(as.matrix(tdm))), 50)), ]
tdm

dtm <- dtm[, names(tail(sort(colSums(as.matrix(dtm))), 50))]
inspect(dtm)
```


```{r}
dtmss <- removeSparseTerms(dtm, 0.15)    
```

```{r}
library(cluster)   
library(fpc)   
d <- dist(t(dtmss), method="euclidian")   
kfit <- kmeans(d, 3)   
clusplot(as.matrix(d), kfit$cluster, color=T, shade=T, labels=2, lines=0)     
```

